name: test_site
description: Herzlich wilkommen bei SYKZ.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"


dependencies:
  beamer: ^1.5.2
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_svg:
  scrollable_positioned_list: ^0.3.2
  scroll_to_index: ^3.0.1
  provider: ^6.0.3
  flutter_staggered_animations: ^1.1.1
  visibility_detector: ^0.3.3
  animated_text_kit: ^4.2.2
  url_launcher: ^6.1.6
  file_picker_cross: ^4.6.0

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
  build_runner:
  flutter_gen_runner:

flutter_gen:
  # Optional
  output: lib/gen/
  # Optional
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false

  assets:
    # Optional
    enabled: true
    # Optional
    # Set to true if you want this package to be a package dependency
    # See: https://flutter.dev/docs/development/ui/assets-and-images#from-packages
    package_parameter_enabled: false
    # Optional
    # Avaliable values:
    # - camel-case
    # - snake-case
    # - dot-delimiter
    style: dot-delimiter

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
        - asset: assets/fonts/montserrat/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/montserrat/Montserrat-LightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/montserrat/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
        - asset: assets/fonts/montserrat/Montserrat-ThinItalic.ttf
    - family: Futura
      fonts:
        - asset: assets/fonts/futura/futur.ttf
        - asset: assets/fonts/futura/Futura Bold font.ttf
        - asset: assets/fonts/futura/Futura Bold Italic font.ttf
        - asset: assets/fonts/futura/Futura Light Italic font.ttf
        - asset: assets/fonts/futura/futura medium bt.ttf
        - asset: assets/fonts/futura/Futura Medium Italic font.ttf
        - asset: assets/fonts/futura/Futura XBlk BT.ttf
        - asset: assets/fonts/futura/Futura-CondensedLight.otf
        - asset: assets/fonts/futura/tt0205m_.ttf
        - asset: assets/fonts/futura/unicode.futurabb.ttf
    - family: Celesta
      fonts:
        - asset: assets/fonts/celesta/Celesta-Bold.otf
        - asset: assets/fonts/celesta/Celesta-BoldOblique.otf
        - asset: assets/fonts/celesta/Celesta-ExtraBold.otf
        - asset: assets/fonts/celesta/Celesta-ExtraBoldOblique.otf
        - asset: assets/fonts/celesta/Celesta-Medium.otf
        - asset: assets/fonts/celesta/Celesta-MediumOblique.otf
        - asset: assets/fonts/celesta/Celesta-Regular.otf
        - asset: assets/fonts/celesta/Celesta-RegularOblique.otf
        - asset: assets/fonts/celesta/Celesta-SemiBold.otf
        - asset: assets/fonts/celesta/Celesta-SemiBoldOblique.otf

  assets:
    - assets/images/
    - assets/icons/


